import "~/styles/globals.css";

import { GeistSans } from 'geist/font'
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "./_components/providers";

export const metadata = {
  title: "Todoing",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`} suppressHydrationWarning>
        <body>
          <Providers>
            <Header />
            <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
