import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "./_components/providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Todoing",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <Providers>
            <Header />
            <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
